import type { ThinPlace } from './ThinPlaces'

/**
 * Seed data for fixed Thin Places: historically and mythologically
 * significant locations associated with crossroads, ancient ritual sites,
 * and places referenced in goetic tradition.
 *
 * All have veilStrength 0.15–0.35 (quite potent).
 */
export const FIXED_THIN_PLACES: ThinPlace[] = [
  {
    id: 'stonehenge',
    type: 'fixed',
    center: { lat: 51.1789, lng: -1.8262 },
    radiusMeters: 200,
    veilStrength: 0.15,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'crossroads-clarksdale',
    type: 'fixed',
    center: { lat: 33.7498, lng: -90.6837 },
    radiusMeters: 150,
    veilStrength: 0.20,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'glastonbury-tor',
    type: 'fixed',
    center: { lat: 51.1447, lng: -2.6977 },
    radiusMeters: 250,
    veilStrength: 0.22,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'carnac-stones',
    type: 'fixed',
    center: { lat: 47.5887, lng: -3.0814 },
    radiusMeters: 300,
    veilStrength: 0.25,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'ayers-rock',
    type: 'fixed',
    center: { lat: -25.3444, lng: 131.0369 },
    radiusMeters: 400,
    veilStrength: 0.18,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'hekla-volcano',
    type: 'fixed',
    center: { lat: 63.9826, lng: -19.6658 },
    radiusMeters: 500,
    veilStrength: 0.20,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'teotihuacan',
    type: 'fixed',
    center: { lat: 19.6925, lng: -98.8438 },
    radiusMeters: 350,
    veilStrength: 0.22,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'mount-sinai',
    type: 'fixed',
    center: { lat: 28.5396, lng: 33.9749 },
    radiusMeters: 300,
    veilStrength: 0.25,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'new-orleans-crossroads',
    type: 'fixed',
    center: { lat: 29.9511, lng: -90.0715 },
    radiusMeters: 200,
    veilStrength: 0.25,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'delphi',
    type: 'fixed',
    center: { lat: 38.4821, lng: 22.5011 },
    radiusMeters: 250,
    veilStrength: 0.18,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sewers-of-paris',
    type: 'fixed',
    center: { lat: 48.8584, lng: 2.2945 },
    radiusMeters: 150,
    veilStrength: 0.30,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'aksum-obelisks',
    type: 'fixed',
    center: { lat: 14.1270, lng: 38.7201 },
    radiusMeters: 200,
    veilStrength: 0.28,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'perm-anomalous-zone',
    type: 'fixed',
    center: { lat: 57.8615, lng: 55.9218 },
    radiusMeters: 500,
    veilStrength: 0.20,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'callanish-stones',
    type: 'fixed',
    center: { lat: 58.1979, lng: -6.7447 },
    radiusMeters: 200,
    veilStrength: 0.22,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'roslyn-chapel',
    type: 'fixed',
    center: { lat: 55.8553, lng: -3.1586 },
    radiusMeters: 100,
    veilStrength: 0.30,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'chichen-itza',
    type: 'fixed',
    center: { lat: 20.6843, lng: -88.5678 },
    radiusMeters: 300,
    veilStrength: 0.22,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'great-zimbabwe',
    type: 'fixed',
    center: { lat: -20.2692, lng: 30.9350 },
    radiusMeters: 250,
    veilStrength: 0.28,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'lake-titicaca-isla-del-sol',
    type: 'fixed',
    center: { lat: -16.0228, lng: -69.1850 },
    radiusMeters: 300,
    veilStrength: 0.25,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'newgrange',
    type: 'fixed',
    center: { lat: 53.6947, lng: -6.4757 },
    radiusMeters: 200,
    veilStrength: 0.20,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'externsteine',
    type: 'fixed',
    center: { lat: 51.8687, lng: 8.9175 },
    radiusMeters: 150,
    veilStrength: 0.28,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
]
