import type { ThinPlace } from './ThinPlaces'

/**
 * Seed data for fixed Thin Places in Old Town Sibiu (Centrul Istoric),
 * Romania — medieval churches, towers, squares, and passages with
 * deep occult resonance in the Transylvanian tradition.
 *
 * All coordinates fall within the historic centre (~45.794–45.800 N,
 * 24.147–24.154 E).  Veil strengths 0.14–0.30 (potent locations).
 */
export const FIXED_THIN_PLACES: ThinPlace[] = [
  {
    id: 'sibiu-evangelical-cathedral',
    type: 'fixed',
    center: { lat: 45.7972, lng: 24.1520 },
    radiusMeters: 60,
    veilStrength: 0.15,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-council-tower',
    type: 'fixed',
    center: { lat: 45.7975, lng: 24.1510 },
    radiusMeters: 30,
    veilStrength: 0.18,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-holy-trinity-cathedral',
    type: 'fixed',
    center: { lat: 45.7962, lng: 24.1488 },
    radiusMeters: 50,
    veilStrength: 0.16,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-liar-bridge',
    type: 'fixed',
    center: { lat: 45.7978, lng: 24.1507 },
    radiusMeters: 25,
    veilStrength: 0.22,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-piata-mare',
    type: 'fixed',
    center: { lat: 45.7977, lng: 24.1527 },
    radiusMeters: 80,
    veilStrength: 0.25,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-piata-mica',
    type: 'fixed',
    center: { lat: 45.7980, lng: 24.1505 },
    radiusMeters: 50,
    veilStrength: 0.28,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-piata-huet',
    type: 'fixed',
    center: { lat: 45.7966, lng: 24.1524 },
    radiusMeters: 45,
    veilStrength: 0.20,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-stairs-passage',
    type: 'fixed',
    center: { lat: 45.7973, lng: 24.1497 },
    radiusMeters: 20,
    veilStrength: 0.19,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-pharmacy-museum',
    type: 'fixed',
    center: { lat: 45.7979, lng: 24.1530 },
    radiusMeters: 20,
    veilStrength: 0.24,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-brukenthal-palace',
    type: 'fixed',
    center: { lat: 45.7976, lng: 24.1535 },
    radiusMeters: 40,
    veilStrength: 0.26,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-ursuline-church',
    type: 'fixed',
    center: { lat: 45.7958, lng: 24.1507 },
    radiusMeters: 30,
    veilStrength: 0.17,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-thick-tower',
    type: 'fixed',
    center: { lat: 45.7953, lng: 24.1477 },
    radiusMeters: 30,
    veilStrength: 0.20,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-potters-tower',
    type: 'fixed',
    center: { lat: 45.7948, lng: 24.1500 },
    radiusMeters: 25,
    veilStrength: 0.23,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-carpenters-tower',
    type: 'fixed',
    center: { lat: 45.7945, lng: 24.1520 },
    radiusMeters: 25,
    veilStrength: 0.22,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-night-asylum',
    type: 'fixed',
    center: { lat: 45.7988, lng: 24.1492 },
    radiusMeters: 25,
    veilStrength: 0.30,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-fingerling-stiege',
    type: 'fixed',
    center: { lat: 45.7969, lng: 24.1493 },
    radiusMeters: 15,
    veilStrength: 0.21,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-haller-bastion',
    type: 'fixed',
    center: { lat: 45.7943, lng: 24.1513 },
    radiusMeters: 40,
    veilStrength: 0.19,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-goldsmith-tower',
    type: 'fixed',
    center: { lat: 45.7985, lng: 24.1475 },
    radiusMeters: 25,
    veilStrength: 0.23,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-franciscan-church',
    type: 'fixed',
    center: { lat: 45.7992, lng: 24.1517 },
    radiusMeters: 35,
    veilStrength: 0.14,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
  {
    id: 'sibiu-old-town-hall',
    type: 'fixed',
    center: { lat: 45.7974, lng: 24.1522 },
    radiusMeters: 30,
    veilStrength: 0.27,
    createdAt: 0,
    createdBy: null,
    ritualActivity: 0,
  },
]
